#Podfile

source 'https://github.com/CocoaPods/Specs.git'

platform :ios,’8.0’
use_frameworks!
inhibit_all_warnings!

target ‘ScaledPageView’ do

pod 'SnapKit', '~> 0.21.0'
pod 'EZSwiftExtensions'
end